name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    outputs:
      image_name: ${{ steps.image.outputs.image_name }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: image
        run: echo image_name=${{ vars.DOCKER_REGISTRY }}/${{ github.repository }} >> $GITHUB_OUTPUT

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ steps.image.outputs.image_name }}:latest
          cache-from: type=registry,ref=${{ steps.image.outputs.image_name }}-buildcache:${{ github.ref_name }}
          cache-to: type=registry,ref=${{ steps.image.outputs.image_name }}-buildcache:${{ github.ref_name }},mode=max

  deploy:
    name: Deploy
    needs:
      - build
    environment:
      name: ${{ github.ref_name }}
      url: https://${{ vars.DEPLOY_HOST }}/
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Configure docker-compose.yml
        run: |
          docker compose config > docker-compose.configured.yml
        env:
          DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}
          IMAGE: ${{ needs.build.outputs.image_name }}
          TAG: latest

      - name: Deploy
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ vars.SERVER }} "mkdir -p ${{ github.repository }}"
          scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no docker-compose.configured.yml ${{ secrets.SSH_USER }}@${{ vars.SERVER }}:${{ github.repository }}/docker-compose.yml
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ vars.SERVER }} "cd ${{ github.repository }} && docker login ${{ vars.DOCKER_REGISTRY }} -u ${{ github.repository_owner }} -p ${{ github.token }} && docker compose pull && docker compose up -d"

      - name: Cleanup images
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ vars.SERVER }} "docker image prune -af"
        continue-on-error: true

